# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-24 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('name', models.CharField(max_length=150)),
                ('genre', models.ManyToManyField(to='apiv1.Genre')),
            ],
        ),
    ]
